apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: drax16
  name: draxapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: drax16
  type: LoadBalancer
status:
  loadBalancer: {}
